nombre = input('Ingrese su nombre: ')
apellido = input('Ingrese su apellido: ')
codigo = input('Ingrese su Código-sección: ')
sede = input('Ingrese su sede: ')
print(f'Nombre: {nombre} {apellido}, Código: {codigo}, Sede: {sede}')
